events {
    worker_connections 1024;
}

http {
    map $arg_tenant $version {
        default "v0";
        tenant1 "v1";
        tenant2 "v2";
    }

    server {
        listen 80;

        location /tenantVersion {
            return 200 $version;
        }
    }
}
