load_module /usr/lib/nginx/modules/ngx_http_js_module.so;

events {
    worker_connections 1024;
}

http {
    js_path "/etc/nginx/njs/";
    js_import main from http/tenant-file-serving/main.js;

    upstream config_service {
        server config:80;
    }

    server {
        listen 80;

        location /files/cer {
            js_content main.get_file;
        }

        location /config {
            internal;
            proxy_pass http://config_service/tenantVersion?$args;
        }

        location /invalidate {
            js_content main.invalidate_cache;
        }
    }
}
